PassionPortfolio/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace PassionPortfolio.Models
{
    public class User
    {
        [Key]
        public int UserId { get; set; }
        //User first name
        [Required, StringLength(255), Display(Name = "First Name")]
        public string UserFname { get; set; }
        //User last name
        [Required, StringLength(255), Display(Name = "Last Name")]
        public string UserLname { get; set; }
        //usre email
        [Required, StringLength(255), Display(Name = "Email")]
        public string UserEmail { get; set; }
        //User contact
        [Required, StringLength(255), Display(Name = "Contact No.")]
        public string UserContact { get; set; }

        //profile picture
        //1=>picture exists (in imgs/authors/{id}.img)
        //0=>picture doesn't exist
        //public int HasPic { get; set; }

        //Accepted image formats (jpg/jpeg/png/gif)
        //public string ImgType { get; set; }


        public virtual ICollection<Project> Projects { get; set; }
    }
}

PassionPortfolio/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;
using System.Data.Entity;
using PassionPortfolio.Models;
using System.Net;
using PassionPortfolio.Models.View_Models;

namespace PassionPortfolio.Controllers
{
    public class ProjectController : Controller
    {
        private PassionProjectCMSContext db = new PassionProjectCMSContext();
        // GET: Project
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult New()
        {
            //Connection to DB needed to grant list of users
            //ask user to pick which user developed the project

            ProjectEdit projecteditview = new ProjectEdit();
            projecteditview.users = db.Users.ToList();

            return View(projecteditview);
        }
        [HttpPost]//after submit
        public ActionResult Create(string ProjectTitle_New, string ProjectDesc_New, string ProjectLink_New, int ProjectUser_New)
        {
            //Standard query representation   
            string query = "insert into Projects (ProjectTitle, ProjectDesc, ProjectLink, user_UserId) values (@ptitle, @pdesc, @plink, @author)";
            SqlParameter[] myparams = new SqlParameter[4];
            myparams[0] = new SqlParameter("@ptitle", ProjectTitle_New);
            myparams[1] = new SqlParameter("@pdesc", ProjectDesc_New);
            myparams[2] = new SqlParameter("@plink", ProjectLink_New);
            myparams[3] = new SqlParameter("@author", ProjectUser_New);

            //putting that information into the database by running a command
            db.Database.ExecuteSqlCommand(query, myparams);

            return RedirectToAction("List");
        }
        public ActionResult List()
        {
            string query = "select * from Projects";
            //This function needs to print out a list of the projects
            IEnumerable<Project> projects = db.Projects.SqlQuery(query);//list of project
            return View(projects);
        }
        public ActionResult Edit(int id)
        {

            ProjectEdit projecteditview = new ProjectEdit();
            projecteditview.users = db.Users.ToList();//For edit we need list of users
            projecteditview.project = db.Projects.Find(id);

            return View(projecteditview);
        }

        [HttpPost]
        public ActionResult Edit(int id, string ProjectTitle_New, string ProjectDesc_New, string ProjectLink_New, int ProjectUser_New)
        {
            //If the ID doesn't exist or the project doesn't exist
            if ((id == null) || (db.Projects.Find(id) == null))
            {
                return HttpNotFound();

            }//Way to avoid sql Injection attack
            string query = "update Projects set ProjectTitle=@ptitle, ProjectDesc=@pdesc, ProjectLink=@plink, user_UserId=@author where ProjectId=@id";
            SqlParameter[] myparams = new SqlParameter[5];
            myparams[0] = new SqlParameter("@ptitle", ProjectTitle_New);
            myparams[1] = new SqlParameter("@pdesc", ProjectDesc_New);
            myparams[2] = new SqlParameter("@plink", ProjectLink_New);
            myparams[3] = new SqlParameter("@author", ProjectUser_New);
            myparams[4] = new SqlParameter("@id", id);

            db.Database.ExecuteSqlCommand(query, myparams);

            return RedirectToAction("Details/" + id);
        }
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if ((id == null) || (db.Projects.Find(id) == null))
            {
                return HttpNotFound();

            }

            //Delete Project
            string query = "delete from Projects where ProjectId=@id";
            SqlParameter param = new SqlParameter("@id", id);
            db.Database.ExecuteSqlCommand(query, param);
            return RedirectToAction("List");
        }
    }
}

PassionPortfolio/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;
using System.Data.Entity;
using PassionPortfolio.Models;
using System.Net;
namespace PassionPortfolio.Controllers
{
    public class UserController : Controller
    {
        private PassionProjectCMSContext db = new PassionProjectCMSContext();
        // GET: User
        public ActionResult Index()
        {
            return View(RedirectToAction("List"));
        }

        public ActionResult New()
        {

            return View();
        }
        [HttpPost]
        public ActionResult Create(string UserFname_New, string UserLname_New, string UserContact_New, string UserEmail_New)
        {
            //Standard query representation   
            string query = "insert into Users (UserFname, UserLname, UserContact, UserEmail) values (@fname, @lname, @contact, @email)";
            SqlParameter[] myparams = new SqlParameter[4];
            myparams[0] = new SqlParameter("@fname", UserFname_New);
            myparams[1] = new SqlParameter("@lname", UserLname_New);
            myparams[2] = new SqlParameter("@contact", UserContact_New);
            myparams[3] = new SqlParameter("@email", UserEmail_New);


            //putting that information into the database by running a command
            db.Database.ExecuteSqlCommand(query, myparams);

            return RedirectToAction("List");
        }
        public ActionResult List()
        {//List of users from Users table
            string query = "select * from Users";
            IEnumerable<User> users = db.Users.SqlQuery(query);//query fire on table

            return View(users);
            
        }
        public ActionResult Edit(int? id)
        {

            if ((id == null) || (db.Users.Find(id) == null))
            {
                return HttpNotFound();
            }
            string query = "select * from Users where UserId=@id";
            SqlParameter param = new SqlParameter("@id", id);
            User myuser = db.Users.SqlQuery(query, param).FirstOrDefault();
            return View(myuser);
        }

        [HttpPost]
        public ActionResult Edit(int? id, string UserFname_New, string UserLname_New, string UserContact_New, string UserEmail_New)
        {

            if ((id == null) || (db.Users.Find(id) == null))
            {
                return HttpNotFound();
            }
            string query = "update Users set UserFname=@fname, UserLname=@lname, UserEmail=@email, UserContact=@contact where UserId=@id";
            SqlParameter[] myparams = new SqlParameter[5];
            myparams[0] = new SqlParameter("@fname", UserFname_New);
            myparams[1] = new SqlParameter("@lname", UserLname_New);
            myparams[2] = new SqlParameter("@contact", UserContact_New);
            myparams[3] = new SqlParameter("@email", UserEmail_New);
            myparams[4] = new SqlParameter("@id", id);

            db.Database.ExecuteSqlCommand(query, myparams);

            return RedirectToAction("Details/" + id);
        }

        // GET: Users/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("List");
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

    }
}

PassionPortfolio/Views/User/Delete.cshtml
@model PassionPortfolio.Models.User

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Student</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Name: 
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserFname) @Html.DisplayFor(model => model.UserFname)
        </dd>

        <dt>
            Email: 
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserEmail)
        </dd>

        <dt>
            Contact: 
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserContact)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "List")
        </div>
    }
</div>

PassionPortfolio/Views/User/Details.cshtml
@model PassionPortfolio.Models.User

@{
    ViewBag.Title = "Details";
}

<h2>User Information</h2>

<div class="card" style="width: 18rem;">
    <img class="card-img-top" src="" alt="Profile Picture">
    <div class="card-body">
        <h4 class="card-title"><strong>@Model.UserFname @Model.UserLname</strong></h4>
        <p class="card-text"><strong>Email: </strong>@Model.UserEmail</p>
        <p class="card-text"><strong>Contact: </strong> @Model.UserContact</p>
        <span class="btn btn-light">@Html.ActionLink("Edit Profile", "Edit", new { id = Model.UserId })</span>
        <span class="btn btn-light">@Html.ActionLink("Delete", "Delete", new { id = Model.UserId })</span>
        <span class="btn btn-light">@Html.ActionLink("Add Project", "New", "Project")</span>
    </div>
</div>

PassionPortfolio/Views/User/Edit.cshtml
@model PassionPortfolio.Models.User

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>
<form method="POST" action="/User/Edit/@Model.UserId">
    <div class="form-group">
        <label for="UserFname_New">First Name</label>
        <input id="UserFname_New" type="text" value="@Model.UserFname" class="form-control" name="UserFname_New" />
        <label for="UserLname_New">Last Name</label>
        <input id="UserLname_New" type="text" value="@Model.UserLname" class="form-control" name="UserLname_New" />
    </div>
    <div class="form-group">
        <label for="UserContact_New">Contact</label>
        <input id="UserContact_New" type="text" value="@Model.UserContact" class="form-control" name="UserContact_New" />
    </div>
    <div class="form-group">
        <label for="UserEmail_New">Email</label>
        <input id="UserEmail_New" type="email" value="@Model.UserEmail" class="form-control" name="UserEmail_New" />

    </div>



    <input type="submit" class="btn btn-primary" value="Save" />
    <li class="btn btn-light">@Html.ActionLink("Cancel", "List")</li>
</form>

PassionPortfolio/Views/User/List.cshtml
@model IEnumerable<PassionPortfolio.Models.User>

@{
    ViewBag.Title = "List";
}

<h2>Students List</h2>
<hr />
<li class="btn btn-light" >@Html.ActionLink("Add Student", "New")</li>
<table class="table">
    <thead class="thead-dark">
        <tr>
            <th scope="col">
                First Name
            </th>
            <th scope="col">
                Last Name
            </th>
            <th scope="col">
                Email
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
         {
             <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.UserFname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UserLname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UserEmail)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.UserId }) |
                    @Html.ActionLink("Details", "Details", new { id = item.UserId }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.UserId })
                </td>
            </tr>
         }
    </tbody>
</table>

PassionPortfolio/Views/User/New.cshtml
@model PassionPortfolio.Models.User

@{
    ViewBag.Title = "Create";
}

<h2>New Student</h2>
<form method="POST" action="/User/Create">
    <div class="form-group">
        <label for="UserFname_New">First Name</label>
        <input id="UserFname_New" type="text" class="form-control" name="UserFname_New" />
        <label for="UserLname_New">Last Name</label>
        <input id="UserLname_New" type="text" class="form-control" name="UserLname_New" />
    </div>
    <div class="form-group">
        <label for="UserContact_New">Contact</label>
        <input id="UserContact_New" type="text" class="form-control" name="UserContact_New" />
    </div>
    <div class="form-group">
        <label for="UserEmail_New">Email</label>
        <input id="UserEmail_New" type="email" class="form-control" name="UserEmail_New" />

    </div>
    <input type="submit" class="btn btn-primary" value="Submit" />
    </form>